name: animestore
description: Anime Store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/product_1.png
    - assets/images/product_2.png
    - assets/images/product_3.png
    - assets/images/product_4.png
    - assets/images/product_5.png
    - assets/images/product_6.png
    - assets/images/product_7.png
    - assets/images/product_8.png
    - assets/images/product_9.png
    - assets/images/product_10.png
    - assets/images/product_11.png
    - assets/images/product_12.png
    - assets/images/product_13.png
    - assets/images/product_14.png
    - assets/images/product_15.png
    - assets/images/product_16.png
    - assets/images/product_17.png
    - assets/images/product_18.png
    - assets/images/product_19.png
    - assets/images/hoodie_1.png
    - assets/images/hoodie_2.png
    - assets/images/hoodie_3.png
    - assets/images/hoodie_4.png
    - assets/images/hoodie_5.png
    - assets/images/hoodie_6.png
    - assets/images/hoodie_7.png
    - assets/images/hoodie_8.png
    - assets/images/cat_demon_slayer.png
    - assets/images/cat_bleach.png
    - assets/images/cat_chainsaw_man.png
    - assets/images/cat_attack_on_titan.png
    - assets/images/cat_hunter_x_hunter.png
    - assets/images/cat_jujutsu_kaisen.png
    - assets/images/cat_solo_leveling.png
    - assets/images/cat_kaiju_8.png
    - assets/images/cat_dr_stone.png
    - assets/images/cat_mashle.png
    - assets/images/cat_hoodie.png